\c retro_games;



INSERT INTO games (name, console, price, release_date, favorites, box_image) VALUES																									
																									
('Super Mario World', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/6/6a/Super_Mario_64_box_cover.jpg'),																									
('Die Hard', 'Commodore 64', 40, 1992, true, 'https://commondatastorage.googleapis.com/images.pricecharting.com/AMIfv96HwWj7h1-A-Z9OAdjI4Ayd1i-4iLBcHUZz_4HrB5XXs8IbyikBVnIBAAJgx_gFSSgtZfp-6iXfF1S9mrOqXpgw1WzqcSE7LFNx5SRvkmFyWn-3_Ntf5VnFx0Z5lE7XHGxiLZHGq6eqE1ZUDh6dwXcIF3NwYQ/240.jpg'),																									
('The Secret of Monkey Island', 'PC', 20, 1993, true, 'https://commondatastorage.googleapis.com/images.pricecharting.com/7695caee17faa659bd1dbd7e67f1f8172ae18d5a62b0114270c383d35c11b2c2/240.jpg'),																									
('Sex Olympics', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/1/1b/Sex_Olympics_Amiga_Box_Art.jpg'),																									
('Lord of the Rings', 'PC', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/e/ee/J.R.R._Tolkien%27s_The_Lord_of_the_Rings%2C_Vol._I_Amiga_cover_art.jpg'),																									
('Metal Gear 2: Solid Snake', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/thumb/1/14/Metal_Gear_2_Boxart.JPG/220px-Metal_Gear_2_Boxart.JPG'),																									
('Total Recall', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/Total_Recall_%28video_game%29_%28Cover%29.jpg/220px-Total_Recall_%28video_game%29_%28Cover%29.jpg'),																									
('Dr. Mario', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://www.videogamer.com/wp-content/uploads/3f2c0068-104b-4961-9fc7-98b7e9c8a3e2_DrMario-1.jpg'),																									
('Days of Thunder', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/8/8b/Days_of_Thunder_cover_art_%28NES%29.jpg'),																									
('Pit-Fighter', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/6/61/ATARI_-_PIT-FIGHTER_1990.jpg'),																									
('Beverly Hills Cop', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'http://3.bp.blogspot.com/-183yPR2lFhA/TcW_faxiNaI/AAAAAAAAEPI/EqCxSV9LsqI/s1600/Beverly_Hills_Cop_C64_01.png'),																									
('Final Fantasy III', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://www.lukiegames.com/assets/images/SNES/snes_final_fantasy_3_p_wgtfw8.jpg'),																									
('Gremlins 2: The New Batch', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/e/e5/Gremlins2nes.PNG'),																									
('Wing Commander', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://www.lukiegames.com/assets/images/SNES/snes_wing_commander_p_nfd9lj.jpg'),																									
('Alien Strom', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/7/7a/Alien_Storm_Cover.jpg'),																									
('Little Nemo: The Dream Master', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://i.ytimg.com/vi/YE_4Q5aBenM/hqdefault.jpg'),																									
('Chip ’n’ Dale: Rescue Rangers', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/0/02/Chip_%27n_Dale_Rescue_Rangers_NES_Cover.png'),																									
('King’s Quest V: Absence Makes the Heart Go Yonder', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/8/80/King%27s_Quest_V_-_Absence_Makes_the_Heart_Go_Yonder%21_Coverart.jpg'),																									
('Ys: Book 1&2', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/e/e1/Ys_Book_1_%26_2.jpg'),																									
('Back to the Future Part II', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/1/15/BTTFIIandIII.jpg'),																									
('Sturmovik: SU-25 Soviet Attack Fighter', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://he-1000-1975.com/wp-content/uploads/2021/05/Su-25-Pic-5.png'),																									
('King’s Quest I: Quest for the Crown', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/7/7f/King%27s_Quest_I_-_Quest_for_the_Crown_Coverart.jpg'),																									
('Super Quest 1: The Sarien Encounter', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://i.ibb.co/PM0C25B/MV5-BYm-Zl-Mj-Iw-Ym-Yt-Y2-M4-OS00-NDIy-LWIw-YWIt-ZGRi-Mz-Uy-ZGI2-Nz-Yw-Xk-Ey-Xk-Fqc-Gde-QXVy-Nj-Ex-O.jpg' ),																									
('DuckTales: The Quest for Gold', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/d/dd/DuckTales_The_Quest_for_Gold.jpg'),																									
('Silver Surfer', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/6/6f/Silver_Surfer_NES_box.jpg'),																									
('Loom', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/f/f1/LOOM_Cover_Art.jpg' ),																									
('The Spy Who Loved Me', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://static.rogerebert.com/uploads/blog_post/primary_image/features/keeping-the-elegant-end-up-the-spy-who-loves-me-at-40/Spy-Loved-Me.jpg'),																									
('Mad Max', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/0/03/Mad_Max_Coverart.png'),																									
('Moonwalker', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/e/ec/Michael_Jackson%27s_Moonwalker_Boxshot.jpg'),																									
('Snake’s Revenge', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://i.ytimg.com/vi/GYKjNOcjDXY/hqdefault.jpg'),																									
('Crime Wave', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/7/76/CrimeWave_Cover.jpg'),																									
('Harlem Globetrotters', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/f/f6/Harlem_Globetrotters_cover.jpg'),																									
('Battle Shark', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true,   'https://i.ibb.co/WsyBrSL/unnamed.png'),																									
('Pictionary: The Game of Video Quick Draw', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://i.ytimg.com/vi/kThlumgN8F0/hqdefault.jpg'),																									
('Toki', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/3/3a/Toki_arcade_flyer.jpg'),																									
('Castle of Illusion', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/f/f4/Castle_of_illusion_Mickey_mouse.jpg'),																									
('Mega Man 3', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://i.ytimg.com/vi/YmfCuZ2DZAI/maxresdefault.jpg'),																									
('The Amazing Spider-Man', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://i.ebayimg.com/images/g/QxgAAMXQDjhQ84I8/s-l640.jpg'),																									
('Street Fighter 2010', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/e/e9/Street_Fighter_Logo.png'),																									
('F-Zero', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/9/9b/SNES_F-Zero_boxart.jpg'),																									
('G-Loc: Air Battle', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/e/e6/G-LOC_-_Air_Battle_%28arcade_promotional_flyer%29.png'),																									
('Nintendo World Cup', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://en.wikipedia.org/wiki/Nintendo_World_Cup#/media/File:Nintendo_World_Cup_Cover.jpg'),																									
('Smash TV', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://www.mobygames.com/images/covers/l/257195-smash-t-v-nes-front-cover.png'),																									
('Gals Panic!', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://www.video-games-museum.com/en/boxart/Saturn/33153_jp-Gals-Panic-SS.jpg'),																									
('Dragon’s Lair', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/5/5c/Dragons_lair.jpg'),																									
('Back to the Future Part II & III', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://www.mobygames.com/images/covers/l/22570-back-to-the-future-part-ii-commodore-64-front-cover.jpg'),																									
('Crystalis', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/9/9b/Crystalisboxart.jpg'),																									
('Rise of the Dragon', 'Super Nintendo Entertainment System (SNES)', 33.99, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Rise_of_the_Dragon_Game_Cover.JPG/240px-Rise_of_the_Dragon_Game_Cover.JPG'),																									
('Thunder Force III', 'Super Nintendo Entertainment System (SNES)', 33, 1990, true, 'https://upload.wikimedia.org/wikipedia/en/2/28/Thunder_Force_III_cover.jpg');																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									